### PR TITLE
1 update samples

### PR DESCRIPTION
**Pull request by Johansmm**
Features:  
* Fix links in BaseDatasets with news datasets.
* Update Sintel and Flying datasets to use `sample ` attribute.
* Update unittest, with `samples = True`

Note:
There is a problem with WaymoDataset sample. In unittest/test_frame.py, a error is launch when sample is used: 

```
Traceback (most recent call last):
  File "unittest/test_frame.py", line 523, in <module>
    test_frame_crop()
  File "unittest/test_frame.py", line 134, in test_frame_crop
    cropped_frame = frame[0, :, 400:900, 500:800]
  File "/home/johan/work/aloception/aloscene/tensors/augmented_tensor.py", line 225, in __getitem__
    name_to_n_label[name] = self.apply_on_label(
  File "/home/johan/work/aloception/aloscene/tensors/augmented_tensor.py", line 93, in apply_on_label
    return _apply_on_label(label, _func, on_list)
  File "/home/johan/work/aloception/aloscene/tensors/augmented_tensor.py", line 88, in _apply_on_label
    result = func(label)
  File "/home/johan/work/aloception/aloscene/tensors/augmented_tensor.py", line 92, in <lambda>
    _func = lambda l: None if l is None else func(l)
  File "/home/johan/work/aloception/aloscene/tensors/augmented_tensor.py", line 226, in <lambda>
    label, lambda l: self._getitem_label(l, name, idx), on_list=False
  File "/home/johan/work/aloception/aloscene/tensors/spatial_augmented_tensor.py", line 559, in _getitem_label
    label = _slice_list(label, 0, label_dim_idx, slicer)
  File "/home/johan/work/aloception/aloscene/tensors/spatial_augmented_tensor.py", line 510, in _slice_list
    n_slice = self.get_slices({label_list.names[dim_idx]: slicer}, label_list)
  File "/home/johan/work/aloception/aloscene/tensors/augmented_tensor.py", line 672, in get_slices
    assert not any(
AssertionError: One of the desired slice dim name is not in the current names of this augmented tensor.
```

Merge until this problem is solved.

### CODE REVIEW

**Review by thibo73800 — CHANGES_REQUESTED** [review]
Thanks, before to merge. In order to be consistent with other __main__ method, I think we must make sure that all __main__ of each datasets used the sample instead of the real dataset.

**Comment by Johansmm** [comment]
Done

**Comment by Johansmm** [comment]
@thibo73800 all datasets was tested with .get, .getitem, stream_loader and train_loader functions.
Also, the download links were tested.
Ready to review

**Review by thibo73800 — APPROVED** [review]
Ok to be merged, should I update the online sample with /data/samples ?

**Comment by thibo73800** [comment]
Unit tests do not work  on my side. Maybe because I need to update the sample first ?

**Review by thibo73800 — APPROVED** [review]

**Pull request merged**
